### ISSUE TITLE
ros2bag2video.py script gets stuck Python 3.10, ros2 humble, Ubuntu 22.04 in converting color raw bag to video

### ISSUE THREAD

**Issue by zehranrgi** [mlaiacker/rosbag2video#38] opened 2024-04-03 07:56 UTC
Is there any update?

_Originally posted by @zehranrgi in https://github.com/mlaiacker/rosbag2video/issues/36#issuecomment-2033813268_

**Comment by cardboardcode** [comment] 2024-10-12 04:25
Duplicate of linked issue 36. Closing.

**Closed by cardboardcode** 2024-10-12 04:25 UTC
